apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: academic-postgres-data
  namespace: academic-management
  labels:
    app.kubernetes.io/name: academic-postgres
    app.kubernetes.io/part-of: academic-management
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
