apiVersion: v1
kind: Secret
metadata:
  name: academic-postgres-secret
  namespace: academic-management
  labels:
    app.kubernetes.io/name: academic-postgres
    app.kubernetes.io/part-of: academic-management
type: Opaque
stringData:
  POSTGRES_DB: academic_management
  POSTGRES_USER: academic_user
  POSTGRES_PASSWORD: replace_with_lab_database_password
