apiVersion: v1
kind: Secret
metadata:
  name: academic-backend-secret
  namespace: academic-management
  labels:
    app.kubernetes.io/name: academic-management-api
    app.kubernetes.io/part-of: academic-management
type: Opaque
stringData:
  APP_KEY: base64:replace_with_generated_laravel_key
  DB_USERNAME: academic_user
  DB_PASSWORD: replace_with_database_password
