apiVersion: v1
kind: Service
metadata:
  name: academic-backend
  namespace: academic-management
  labels:
    app.kubernetes.io/name: academic-management-api
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: academic-management
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: academic-management-api
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: 8000
      targetPort: http
