apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: academic-frontend
  namespace: academic-management
  labels:
    app.kubernetes.io/name: academic-management-web
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: academic-management
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: academic-frontend
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
